<a href="https://colab.research.google.com/github/harshikala/AI_Engineer_Journey/blob/main/AIDay1_Harshi_Kala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1.⁠ ⁠Checking NumPy Version
####Import NumPy.
####Print the installed NumPy version.

In [1]:
import numpy as np
print(np.__version__)

2.0.2


##2.⁠ ⁠Creating an Array
####Create a string array with Apple, Orange, Mango, Banana.
####Create a 1D integer array [10,20,30,40,50].
####Create a float array [10.5,20.3,15.7,18.9].

In [2]:
fruits = np.array(["Apple", "Orange", "Mango", "Banana"])
nums = np.array([10, 20, 30, 40, 50])
nums2 = np.array([10.5, 20.3, 15.7, 18.9])

In [5]:
print(fruits.dtype)
print(nums.dtype)
print(nums2.dtype)

<U6
int64
float64


##3.⁠ ⁠Different Dimensions
####Create a 1D array.
####Create a 2D array [[10,20,30],[40,50,60]].
####Create a 3D array with two 2x2 matrices.

##4.⁠ ⁠Check Number of Dimensions
####Find the number of dimensions for 1D, 2D and 3D arrays using the appropriate NumPy function.

In [13]:
nums = np.array([10, 20, 30, 40, 50])
matrix = np.array([[10,20,30],[40,50,60]])
matrix_3d = np.array([[[10,20,30],[40,50,60]], [[7, 8, 9], [10, 11, 12]]])

print(f"Array: {nums}, Dimension: {nums.ndim}\n")
print(f"2D Matrix: {matrix}, Dimension: {matrix.ndim}\n")
print(f"3D Matrix: {matrix_3d}, Dimension: {matrix_3d.ndim}\n")

Array: [10 20 30 40 50], Dimension: 1

2D Matrix: [[10 20 30]
 [40 50 60]], Dimension: 2

3D Matrix: [[[10 20 30]
  [40 50 60]]

 [[ 7  8  9]
  [10 11 12]]], Dimension: 3



##5.⁠ ⁠Creating Arrays with Elements and Dimensions
####Create a 1D array using the ndmin parameter.
####Create a 2D array using ndmin.
####Create a 5-dimensional array containing the value 100 and verify its dimensions.

In [14]:
nums_1D = np.array([10, 20, 30, 40, 50], ndmin = 1)
nums_2D = np.array([10, 20, 30, 40, 50], ndmin = 2)
nums_5D = np.array([100], ndmin = 5)

print(f"Array 1D: {nums_1D}, Dimension: {nums_1D.ndim}\n")
print(f"Array 2D: {nums_2D}, Dimension: {nums_2D.ndim}\n")
print(f"Array 5D: {nums_5D}, Dimension: {nums_5D.ndim}\n")

Array 1D: [10 20 30 40 50], Dimension: 1

Array 2D: [[10 20 30 40 50]], Dimension: 2

Array 5D: [[[[[100]]]]], Dimension: 5



##6.⁠ ⁠Accessing Array Elements
####Access the first, third and last elements of a 1D array.
####Access specific elements from a 2D array.
####Access specific elements from a 3D array.



In [16]:
print("1D Array:", nums)
print("First element:", nums[0])
print("Third element:", nums[2])
print("Last element:", nums[-1])

1D Array: [10 20 30 40 50]
First element: 10
Third element: 30
Last element: 50


In [17]:
print("\n2D Array:", matrix)
print("Element at Row 1, Column 2:", matrix[0, 1])
print("Element at Row 2, Column 3:", matrix[1, 2])
print("Element at Row 2, Column 1:", matrix[1, 0])


2D Array: [[10 20 30]
 [40 50 60]]
Element at Row 1, Column 2: 20
Element at Row 2, Column 3: 60
Element at Row 2, Column 1: 40


In [18]:
print("\n3D Array:", matrix_3d)
print("Element at [0][0][1]:", matrix_3d[0, 0, 1])
print("Element at [0][1][2]:", matrix_3d[0, 1, 2])
print("Element at [1][0][2]:", matrix_3d[1, 0, 2])
print("Element at [1][1][1]:", matrix_3d[1, 1, 1])


3D Array: [[[10 20 30]
  [40 50 60]]

 [[ 7  8  9]
  [10 11 12]]]
Element at [0][0][1]: 20
Element at [0][1][2]: 60
Element at [1][0][2]: 9
Element at [1][1][1]: 11


##7.⁠ ⁠Negative Indexing
####Retrieve the last, second last and third last elements from a 1D array.
####Retrieve the last element, second last element and last element of the first row from a 2D array.
##8.⁠ ⁠Array Slicing
####Extract a range of elements.
####Extract the first four elements.
####Extract the last three elements.
####Extract alternate elements.
####Reverse the array.
####Slice rows and columns from a 2D array.


In [19]:
print("Negative Indexing (1D Array):", nums)
print("Last element:", nums[-1])
print("Second last element:", nums[-2])
print("Third last element:", nums[-3])

Negative Indexing (1D Array): [10 20 30 40 50]
Last element: 50
Second last element: 40
Third last element: 30


In [20]:
print("\nNegative Indexing (2D Array):", matrix)
print("Last element:", matrix[-1, -1])
print("Second last element:", matrix[-1, -2])
print("Last element of first row:", matrix[0, -1])


Negative Indexing (2D Array): [[10 20 30]
 [40 50 60]]
Last element: 60
Second last element: 50
Last element of first row: 30


In [21]:
print("\nArray Slicing (1D Array):", nums)
print("Range of elements (index 1 to 3):", nums[1:4])
print("First four elements:", nums[:4])
print("Last three elements:", nums[-3:])
print("Alternate elements:", nums[::2])
print("Reversed array:", nums[::-1])


Array Slicing (1D Array): [10 20 30 40 50]
Range of elements (index 1 to 3): [20 30 40]
First four elements: [10 20 30 40]
Last three elements: [30 40 50]
Alternate elements: [10 30 50]
Reversed array: [50 40 30 20 10]


In [22]:
print("\nArray Slicing (2D Array):", matrix)
print("First row:", matrix[0, :])
print("Second row:", matrix[1, :])
print("First column:", matrix[:, 0])
print("Second column:", matrix[:, 1])
print("First two columns:\n", matrix[:, :2])
print("Entire matrix:\n", matrix[:, :])


Array Slicing (2D Array): [[10 20 30]
 [40 50 60]]
First row: [10 20 30]
Second row: [40 50 60]
First column: [10 40]
Second column: [20 50]
First two columns:
 [[10 20]
 [40 50]]
Entire matrix:
 [[10 20 30]
 [40 50 60]]


##9.⁠ ⁠Data Types
####Create arrays using i, b, u, f, c, m, M and U data types.
####Convert an integer array to float, boolean and string.
####Identify the datatype of a Unicode array.

In [25]:
int_arr = np.array([1, 2, 3], dtype='i')
bool_arr = np.array([1, 0, 1], dtype='b')
unsigned_arr = np.array([10, 20, 30], dtype='u2')
float_arr = np.array([1.5, 2.5, 3.5], dtype='f')
complex_arr = np.array([1+2j, 3+4j], dtype='c')
timedelta_arr = np.array([5, 10, 15], dtype='m8[D]')
datetime_arr = np.array(['2025-01-01', '2025-12-31'], dtype='M8[D]')
unicode_arr = np.array(["Apple", "Banana", "Cherry"], dtype='U')

print("Integer:", int_arr)
print("Boolean:", bool_arr)
print("Unsigned:", unsigned_arr)
print("Float:", float_arr)
print("Complex:", complex_arr)
print("Timedelta:", timedelta_arr)
print("Datetime:", datetime_arr)
print("Unicode:", unicode_arr)

Integer: [1 2 3]
Boolean: [1 0 1]
Unsigned: [10 20 30]
Float: [1.5 2.5 3.5]
Complex: [b'(' b'(']
Timedelta: [ 5 10 15]
Datetime: ['2025-01-01' '2025-12-31']
Unicode: ['Apple' 'Banana' 'Cherry']


In [26]:
arr = np.array([1, 2, 3, 4])

print("\nOriginal:", arr)

print("To Float:", arr.astype(float))
print("To Boolean:", arr.astype(bool))
print("To String:", arr.astype(str))


Original: [1 2 3 4]
To Float: [1. 2. 3. 4.]
To Boolean: [ True  True  True  True]
To String: ['1' '2' '3' '4']


In [27]:
print("\nDatatype of Unicode Array:", unicode_arr.dtype)


Datatype of Unicode Array: <U6


##10.⁠ ⁠Copy and View
####Create a copy of an array and modify the original.
####Create a view of an array and modify the original.
####Use .base to determine ownership of data.

In [31]:
arr = np.array([10, 20, 30, 40])

# Copy
copy_arr = arr.copy()

arr[0] = 100

print("Original:", arr)
print("Copy:", copy_arr)

# View
view_arr = arr.view()

arr[1] = 200

print("\nOriginal:", arr)
print("View:", view_arr)

# Ownership using .base
print("\nCopy Base:", copy_arr.base)
print("View Base:", view_arr.base)

Original: [100  20  30  40]
Copy: [10 20 30 40]

Original: [100 200  30  40]
View: [100 200  30  40]

Copy Base: None
View Base: [100 200  30  40]


##11.⁠ ⁠Shape
####Print the shape of 1D, 2D and 3D arrays.
####Create a (3,4) array using numbers from 1 to 12 and print its shape.

In [32]:
print("1D Shape:", nums.shape)
print("2D Shape:", matrix.shape)
print("3D Shape:", matrix_3d.shape)

1D Shape: (5,)
2D Shape: (2, 3)
3D Shape: (2, 2, 3)


In [33]:
arr = np.arange(1,13).reshape(3,4)

print("\nArray:\n", arr)
print("Shape:", arr.shape)


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


##12.⁠ ⁠Reshaping
####Reshape a 12-element array into 3x4, 2x6 and 2x2x3.
####Flatten the reshaped array.
####Reshape a 24-element array into 2x3x4.


In [34]:
print("Original:", arr)

print("\n3 x 4")
print(arr.reshape(3,4))

print("\n2 x 6")
print(arr.reshape(2,6))

print("\n2 x 2 x 3")
print(arr.reshape(2,2,3))


Original: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

3 x 4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

2 x 6
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

2 x 2 x 3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [35]:
reshaped = arr.reshape(3,4)

print("\nFlatten:")
print(reshaped.flatten())


Flatten:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [36]:
arr24 = np.arange(1,25)

print("\n2 x 3 x 4")
print(arr24.reshape(2,3,4))


2 x 3 x 4
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


##13.⁠ ⁠Joining Arrays
####Join arrays using concatenate().
####Join 2D arrays row-wise and column-wise.
####Use stack(), vstack(), hstack() and dstack() and observe the output shapes.


In [37]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# concatenate
print("Concatenate:")
print(np.concatenate((a,b)))

Concatenate:
[1 2 3 4 5 6]


In [38]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

print("\nRow-wise Concatenate")
print(np.concatenate((arr1, arr2), axis=0))

print("\nColumn-wise Concatenate")
print(np.concatenate((arr1, arr2), axis=1))


Row-wise Concatenate
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Column-wise Concatenate
[[1 2 5 6]
 [3 4 7 8]]


In [39]:
print("\nStack")
stack = np.stack((arr1, arr2))
print(stack)
print("Shape:", stack.shape)

print("\nVertical Stack")
v = np.vstack((arr1, arr2))
print(v)
print("Shape:", v.shape)

print("\nHorizontal Stack")
h = np.hstack((arr1, arr2))
print(h)
print("Shape:", h.shape)

print("\nDepth Stack")
d = np.dstack((arr1, arr2))
print(d)
print("Shape:", d.shape)


Stack
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)

Vertical Stack
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape: (4, 2)

Horizontal Stack
[[1 2 5 6]
 [3 4 7 8]]
Shape: (2, 4)

Depth Stack
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape: (2, 2, 2)


##Additional questions
####Create a 3x3 sales array.
####Check dimensions and shape.
####Access rows, columns and middle element.
####Slice rows.
####Create copy and view.
####Reshape to 1D.
####Join vertically and horizontally.
####Print datatype.

In [40]:
sales = np.array([
    [101, 204, 303],
    [400, 503, 630],
    [720, 840, 990]
])

print("Sales Array:")
print(sales)

# Dimension and Shape

print("\nDimensions:", sales.ndim)
print("Shape:", sales.shape)

# Access Rows

print("\nFirst Row:", sales[0])
print("Second Row:", sales[1])

# Access Columns

print("First Column:", sales[:,0])
print("Second Column:", sales[:,1])

# Middle Element

print("Middle Element:", sales[1,1])

# Slice Rows

print("\nFirst Two Rows:")
print(sales[:2])

# Copy

sales_copy = sales.copy()

# View

sales_view = sales.view()

sales[0,0] = 999

print("\nModified Original:")
print(sales)

print("\nCopy:")
print(sales_copy)

print("\nView:")
print(sales_view)

# Reshape to 1D

print("\nFlattened:")
print(sales.reshape(-1))

# Join Arrays

extra = np.array([
    [1,1,1],
    [2,2,2],
    [3,3,3]
])

print("\nVertical Join")
print(np.vstack((sales, extra)))

print("\nHorizontal Join")
print(np.hstack((sales, extra)))

# Datatype

print("\nDatatype:", sales.dtype)

Sales Array:
[[101 204 303]
 [400 503 630]
 [720 840 990]]

Dimensions: 2
Shape: (3, 3)

First Row: [101 204 303]
Second Row: [400 503 630]
First Column: [101 400 720]
Second Column: [204 503 840]
Middle Element: 503

First Two Rows:
[[101 204 303]
 [400 503 630]]

Modified Original:
[[999 204 303]
 [400 503 630]
 [720 840 990]]

Copy:
[[101 204 303]
 [400 503 630]
 [720 840 990]]

View:
[[999 204 303]
 [400 503 630]
 [720 840 990]]

Flattened:
[999 204 303 400 503 630 720 840 990]

Vertical Join
[[999 204 303]
 [400 503 630]
 [720 840 990]
 [  1   1   1]
 [  2   2   2]
 [  3   3   3]]

Horizontal Join
[[999 204 303   1   1   1]
 [400 503 630   2   2   2]
 [720 840 990   3   3   3]]

Datatype: int64
