<a href="https://colab.research.google.com/github/harshikala/AI_Engineer_Journey/blob/main/Numpy_Day3_Part1_Harshi_Kala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Part A: Broadcasting
##Scalar Broadcasting:
####Add, subtract, multiply, divide, and square every element of a 1D array.

In [1]:
import numpy as np
print("NumPy Version:", np.__version__)

NumPy Version: 2.0.2


In [2]:
print("\n1. Scalar Broadcasting")

arr = np.array([2, 4, 6, 8])

print("Original Array:", arr)
print("Add 5:", arr + 5)
print("Subtract 2:", arr - 2)
print("Multiply by 3:", arr * 3)
print("Divide by 2:", arr / 2)
print("Square:", arr ** 2)


1. Scalar Broadcasting
Original Array: [2 4 6 8]
Add 5: [ 7  9 11 13]
Subtract 2: [0 2 4 6]
Multiply by 3: [ 6 12 18 24]
Divide by 2: [1. 2. 3. 4.]
Square: [ 4 16 36 64]


#### Broadcasting with 2D Arrays: Apply scalar arithmetic to every element of a matrix.

In [3]:
print("\n2. Broadcasting with 2D Array")

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print(matrix)

print("\nAdd 10")
print(matrix + 10)

print("\nSubtract 1")
print(matrix - 1)

print("\nMultiply by 2")
print(matrix * 2)

print("\nDivide by 2")
print(matrix / 2)


2. Broadcasting with 2D Array
[[1 2 3]
 [4 5 6]]

Add 10
[[11 12 13]
 [14 15 16]]

Subtract 1
[[0 1 2]
 [3 4 5]]

Multiply by 2
[[ 2  4  6]
 [ 8 10 12]]

Divide by 2
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


#### Broadcasting with a Row Vector: Add, subtract, multiply, and divide a row vector with a matrix.

In [4]:
print("\n3. Broadcasting with Row Vector")

mat = np.array([[10, 20, 30],
                [40, 50, 60]])

row = np.array([1, 2, 3])

print("Matrix:\n", mat)
print("Row Vector:", row)

print("\nAddition")
print(mat + row)

print("\nSubtraction")
print(mat - row)

print("\nMultiplication")
print(mat * row)

print("\nDivision")
print(mat / row)


3. Broadcasting with Row Vector
Matrix:
 [[10 20 30]
 [40 50 60]]
Row Vector: [1 2 3]

Addition
[[11 22 33]
 [41 52 63]]

Subtraction
[[ 9 18 27]
 [39 48 57]]

Multiplication
[[ 10  40  90]
 [ 40 100 180]]

Division
[[10. 10. 10.]
 [40. 25. 20.]]


#### Broadcasting with a Column Vector: Perform arithmetic between a column vector and a matrix.

In [5]:
print("\n4. Broadcasting with Column Vector")

column = np.array([[1],
                   [2]])

print("Column Vector:\n", column)

print("\nAddition")
print(mat + column)

print("\nSubtraction")
print(mat - column)

print("\nMultiplication")
print(mat * column)

print("\nDivision")
print(mat / column)


4. Broadcasting with Column Vector
Column Vector:
 [[1]
 [2]]

Addition
[[11 21 31]
 [42 52 62]]

Subtraction
[[ 9 19 29]
 [38 48 58]]

Multiplication
[[ 10  20  30]
 [ 80 100 120]]

Division
[[10. 20. 30.]
 [20. 25. 30.]]


#### Broadcasting Between Different Shapes: Broadcast a (4,) array with a (3,4) matrix and analyze the results.

In [6]:
print("\n5. Broadcasting Different Shapes")

a = np.array([1, 2, 3, 4])

b = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90, 100, 110, 120]])

print("Array Shape:", a.shape)
print("Matrix Shape:", b.shape)

result = b + a

print(result)
print("Result Shape:", result.shape)


5. Broadcasting Different Shapes
Array Shape: (4,)
Matrix Shape: (3, 4)
[[ 11  22  33  44]
 [ 51  62  73  84]
 [ 91 102 113 124]]
Result Shape: (3, 4)


#### Broadcasting with 3D Arrays: Broadcast a 1D array across a 3D array and verify the output shape.

In [7]:
print("\n6. Broadcasting with 3D Arrays")

array3d = np.ones((2,3,4))

vector = np.array([1,2,3,4])

result = array3d + vector

print("3D Shape:", array3d.shape)
print("Vector Shape:", vector.shape)
print("Output Shape:", result.shape)


6. Broadcasting with 3D Arrays
3D Shape: (2, 3, 4)
Vector Shape: (4,)
Output Shape: (2, 3, 4)


#### Broadcasting Errors: Predict which shape combinations are compatible and explain any errors.

In [8]:
print("\n7. Broadcasting Errors")

x = np.ones((2,3))
y = np.ones((3,))
z = np.ones((2,2))

print("Compatible Shapes:")
print(x + y)

print("\nIncompatible Shapes:")

try:
    print(x + z)
except ValueError as e:
    print("Error:", e)

print("\nReason:")
print("(2,3) and (3,) are compatible.")
print("(2,3) and (2,2) are not compatible.")


7. Broadcasting Errors
Compatible Shapes:
[[2. 2. 2.]
 [2. 2. 2.]]

Incompatible Shapes:
Error: operands could not be broadcast together with shapes (2,3) (2,2) 

Reason:
(2,3) and (3,) are compatible.
(2,3) and (2,2) are not compatible.


#### Real-world Broadcasting: Apply bonuses, percentage increases, and regional multipliers to a sales dataset.

In [9]:
print("\n8. Real-world Broadcasting")

sales = np.array([[1200,1500,1800],
                  [2100,2500,2800],
                  [3200,3400,3600]])

print("Sales Data")
print(sales)

bonus = 100
print("\nAfter Bonus")
print(sales + bonus)

increase = 1.10
print("\nAfter 10% Increase")
print(sales * increase)

regional = np.array([1.0,1.2,0.9])

print("\nRegional Multipliers")
print(sales * regional)


8. Real-world Broadcasting
Sales Data
[[1200 1500 1800]
 [2100 2500 2800]
 [3200 3400 3600]]

After Bonus
[[1300 1600 1900]
 [2200 2600 2900]
 [3300 3500 3700]]

After 10% Increase
[[1320. 1650. 1980.]
 [2310. 2750. 3080.]
 [3520. 3740. 3960.]]

Regional Multipliers
[[1200. 1800. 1620.]
 [2100. 3000. 2520.]
 [3200. 4080. 3240.]]


##Part B: Matrix Operations


In [10]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print("\nMatrix A")
print(A)

print("\nMatrix B")
print(B)


Matrix A
[[1 2]
 [3 4]]

Matrix B
[[5 6]
 [7 8]]


####Matrix Addition: Add two matrices and compare A+B with B+A.

In [11]:
print("\n1. Matrix Addition")

print("A + B")
print(A + B)

print("\nB + A")
print(B + A)


1. Matrix Addition
A + B
[[ 6  8]
 [10 12]]

B + A
[[ 6  8]
 [10 12]]


#### Matrix Subtraction: Compute A−B and B−A.


In [12]:
print("\n2. Matrix Subtraction")

print("A - B")
print(A - B)

print("\nB - A")
print(B - A)


2. Matrix Subtraction
A - B
[[-4 -4]
 [-4 -4]]

B - A
[[4 4]
 [4 4]]


#### Element-wise Multiplication: Multiply matrices using the * operator.

In [13]:
print("\n3. Element-wise Multiplication")

print(A * B)


3. Element-wise Multiplication
[[ 5 12]
 [21 32]]


#### Matrix Multiplication: Use np.dot(), np.matmul(), and @ operator to multiply matrices.

In [14]:
print("\n4. Matrix Multiplication")

print("Using np.dot()")
print(np.dot(A,B))

print("\nUsing np.matmul()")
print(np.matmul(A,B))

print("\nUsing @ operator")
print(A @ B)


4. Matrix Multiplication
Using np.dot()
[[19 22]
 [43 50]]

Using np.matmul()
[[19 22]
 [43 50]]

Using @ operator
[[19 22]
 [43 50]]


#### Transpose: Find the transpose of a matrix and compare shapes before and after.

In [15]:
print("\n5. Transpose")

print("Original Shape:", A.shape)

AT = A.T

print("Transpose")
print(AT)

print("Transpose Shape:", AT.shape)


5. Transpose
Original Shape: (2, 2)
Transpose
[[1 3]
 [2 4]]
Transpose Shape: (2, 2)


#### Identity Matrix: Create identity matrices and verify A × I = A.

In [16]:
print("\n6. Identity Matrix")

I = np.eye(2)

print(I)

print("\nA x I")
print(A @ I)


6. Identity Matrix
[[1. 0.]
 [0. 1.]]

A x I
[[1. 2.]
 [3. 4.]]


#### Matrix Inverse: Compute the inverse of a matrix and verify A × A⁻¹ equals the identity matrix.

In [17]:
print("\n7. Matrix Inverse")

inverse = np.linalg.inv(A)

print("Inverse")
print(inverse)

print("\nA x A^-1")
print(A @ inverse)


7. Matrix Inverse
Inverse
[[-2.   1. ]
 [ 1.5 -0.5]]

A x A^-1
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


#### Determinant: Calculate determinants of multiple matrices.

In [18]:
print("\n8. Determinant")

print("Determinant of A:", np.linalg.det(A))

C = np.array([[2,4],
              [1,3]])

print("Determinant of C:", np.linalg.det(C))


8. Determinant
Determinant of A: -2.0000000000000004
Determinant of C: 2.0


#### Trace: Compute the trace of a square matrix.

In [19]:
print("\n9. Trace")

print(np.trace(A))


9. Trace
5


#### Rank: Determine the rank of different matrices.

In [20]:
print("\n10. Rank")

print("Rank of A:", np.linalg.matrix_rank(A))

D = np.array([[1,2],
              [2,4]])

print("Rank of D:", np.linalg.matrix_rank(D))


10. Rank
Rank of A: 2
Rank of D: 1


#### Matrix Power: Compute A², A³, and A⁴ using NumPy.

In [21]:
print("\n11. Matrix Power")

print("A^2")
print(np.linalg.matrix_power(A,2))

print("\nA^3")
print(np.linalg.matrix_power(A,3))

print("\nA^4")
print(np.linalg.matrix_power(A,4))


11. Matrix Power
A^2
[[ 7 10]
 [15 22]]

A^3
[[ 37  54]
 [ 81 118]]

A^4
[[199 290]
 [435 634]]


#### Eigenvalues and Eigenvectors: Compute eigenvalues and eigenvectors of a matrix.

In [22]:
print("\n12. Eigenvalues and Eigenvectors")

values, vectors = np.linalg.eig(A)

print("Eigenvalues")
print(values)

print("\nEigenvectors")
print(vectors)


12. Eigenvalues and Eigenvectors
Eigenvalues
[-0.37228132  5.37228132]

Eigenvectors
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
