<a href="https://colab.research.google.com/github/harshikala/AI_Engineer_Journey/blob/main/NumPy_Day2_Part1_Harshi_Kala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Exercise 1: Create Different Types of Arrays
####Create an array containing the first 10 natural numbers.
####Create an array containing all even numbers from 2 to 20.
####Create an array of the first 10 odd numbers.
####Create an array of squares of numbers from 1 to 10.
####Create an array of multiples of 5 less than 100.

In [2]:
import numpy as np

In [3]:
# 1. Array containing the first 10 natural numbers
natural_numbers = np.arange(1, 11)
print("First 10 Natural Numbers:")
print(natural_numbers)

First 10 Natural Numbers:
[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# 2. Array containing all even numbers from 2 to 20
even_numbers = np.arange(2, 21, 2)
print("\nEven Numbers from 2 to 20:")
print(even_numbers)


Even Numbers from 2 to 20:
[ 2  4  6  8 10 12 14 16 18 20]


In [5]:
# 3. Array containing the first 10 odd numbers
odd_numbers = np.arange(1, 20, 2)
print("\nFirst 10 Odd Numbers:")
print(odd_numbers)


First 10 Odd Numbers:
[ 1  3  5  7  9 11 13 15 17 19]


In [6]:
# 4. Array of squares of numbers from 1 to 10
squares = np.arange(1, 11) ** 2
print("\nSquares of Numbers from 1 to 10:")
print(squares)


Squares of Numbers from 1 to 10:
[  1   4   9  16  25  36  49  64  81 100]


In [7]:
# 5. Array of multiples of 5 less than 100
multiples_of_5 = np.arange(5, 100, 5)
print("\nMultiples of 5 Less Than 100:")
print(multiples_of_5)


Multiples of 5 Less Than 100:
[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


##Exercise 2: Array Dimensions
####Create a 1D array containing employee IDs.
####Create a 2D array representing marks of four students in three subjects.
####Create a 3D array representing sales data for two stores, three months and four products.
####Create a 6-dimensional array containing the value 50.

In [8]:
# 1. Create a 1D array containing employee IDs
employee_ids = np.array([101, 102, 103, 104, 105])
print(employee_ids)
print("Dimensions:", employee_ids.ndim)

[101 102 103 104 105]
Dimensions: 1


In [9]:
# 2. Create a 2D array representing marks of four students in three subjects

marks = np.array([
    [85, 90, 88],
    [78, 82, 80],
    [92, 95, 91],
    [75, 79, 83]
])


print(marks)
print("Dimensions:", marks.ndim)

[[85 90 88]
 [78 82 80]
 [92 95 91]
 [75 79 83]]
Dimensions: 2


In [10]:
# 3. Create a 3D array representing sales data for
#    2 stores, 3 months, and 4 products
sales = np.array([
    [
        [120, 150, 180, 200],   # Store 1 - Month 1
        [130, 160, 190, 210],   # Store 1 - Month 2
        [140, 170, 200, 220]    # Store 1 - Month 3
    ],
    [
        [110, 140, 170, 190],   # Store 2 - Month 1
        [120, 150, 180, 200],   # Store 2 - Month 2
        [130, 160, 190, 210]    # Store 2 - Month 3
    ]
])
print(sales)
print("Dimensions:", sales.ndim)

[[[120 150 180 200]
  [130 160 190 210]
  [140 170 200 220]]

 [[110 140 170 190]
  [120 150 180 200]
  [130 160 190 210]]]
Dimensions: 3


In [11]:
# 4. Create a 6-dimensional array containing the value 50

array_6d = np.array([50], ndmin = 6)
print(array_6d)
print("Dimensions:", array_6d.ndim)

[[[[[[50]]]]]]
Dimensions: 6


##Exercise 3: Accessing Elements
####Access elements from 1D, 2D and 3D arrays using positive indexing.
####Find specific rows, columns and middle elements.

In [12]:
print("1D Array:", employee_ids)

print("First Employee ID:", employee_ids[0])
print("Third Employee ID:", employee_ids[2])
print("Last Employee ID:", employee_ids[4])

1D Array: [101 102 103 104 105]
First Employee ID: 101
Third Employee ID: 103
Last Employee ID: 105


In [13]:
print("\n2D Array (Marks):")
print(marks)

print("Element at Row 1, Column 2:", marks[0, 1])
print("Element at Row 3, Column 1:", marks[2, 0])
print("Element at Row 4, Column 3:", marks[3, 2])


2D Array (Marks):
[[85 90 88]
 [78 82 80]
 [92 95 91]
 [75 79 83]]
Element at Row 1, Column 2: 90
Element at Row 3, Column 1: 92
Element at Row 4, Column 3: 83


In [14]:
print("\n3D Array (Sales Data):")
print(sales)

print("Store 1, Month 2, Product 3:", sales[0, 1, 2])
print("Store 2, Month 3, Product 4:", sales[1, 2, 3])
print("Store 2, Month 1, Product 2:", sales[1, 0, 1])


3D Array (Sales Data):
[[[120 150 180 200]
  [130 160 190 210]
  [140 170 200 220]]

 [[110 140 170 190]
  [120 150 180 200]
  [130 160 190 210]]]
Store 1, Month 2, Product 3: 190
Store 2, Month 3, Product 4: 210
Store 2, Month 1, Product 2: 140


In [15]:
print("\nRows from 2D Array")
print("First Row:", marks[0])
print("Third Row:", marks[2])


Rows from 2D Array
First Row: [85 90 88]
Third Row: [92 95 91]


In [16]:
print("\nColumns from 2D Array")
print("First Column:", marks[:, 0])
print("Second Column:", marks[:, 1])
print("Third Column:", marks[:, 2])


Columns from 2D Array
First Column: [85 78 92 75]
Second Column: [90 82 95 79]
Third Column: [88 80 91 83]


In [17]:
print("\nMiddle Elements")


Middle Elements


In [18]:
print("Middle Employee ID:", employee_ids[len(employee_ids)//2])

Middle Employee ID: 103


In [19]:
print("Middle Element in 2D Array:", marks[1, 1])

Middle Element in 2D Array: 82


In [20]:
print("Middle Product Value in 3D Array:", sales[0, 1, 1])

Middle Product Value in 3D Array: 160


##Exercise 4: Negative Indexing
####Retrieve the last, second last and fourth-from-last elements.
####Access the bottom-right, bottom-left and centre element of a matrix.

In [ ]:
print("1D Array:")
print(employee_ids)

print("\nLast Element:", employee_ids[-1])
print("Second Last Element:", employee_ids[-2])
print("Fourth-from-Last Element:", employee_ids[-4])

In [21]:
print("\n2D Array:")
print(marks)

# Bottom-right element
print("\nBottom-Right Element:", marks[-1, -1])

# Bottom-left element
print("Bottom-Left Element:", marks[-1, 0])

# Centre element
print("Centre Element:", marks[1, 1])


2D Array:
[[85 90 88]
 [78 82 80]
 [92 95 91]
 [75 79 83]]

Bottom-Right Element: 83
Bottom-Left Element: 75
Centre Element: 82


##Exercise 5: Array Slicing
####Extract first five, last five, alternate elements and reverse the array.
####Slice rows, columns, middle matrix and diagonal elements from a 2D array.

In [22]:
print("Employee IDs:", employee_ids)

# First five elements
print("\nFirst Five Elements:", employee_ids[:5])

# Last five elements
print("Last Five Elements:", employee_ids[-5:])

# Alternate elements
print("Alternate Elements:", employee_ids[::2])

# Reverse the array
print("Reversed Array:", employee_ids[::-1])

Employee IDs: [101 102 103 104 105]

First Five Elements: [101 102 103 104 105]
Last Five Elements: [101 102 103 104 105]
Alternate Elements: [101 103 105]
Reversed Array: [105 104 103 102 101]


In [23]:
print("\nMarks Array:")
print(marks)

# Rows
print("\nFirst Two Rows:")
print(marks[:2])

print("\nLast Two Rows:")
print(marks[-2:])

# Columns
print("\nFirst Column:")
print(marks[:, 0])

print("\nSecond Column:")
print(marks[:, 1])

print("\nThird Column:")
print(marks[:, 2])

# Middle Matrix (Rows 2-3 and Columns 2-3)
print("\nMiddle Matrix:")
print(marks[1:3, 1:3])


Marks Array:
[[85 90 88]
 [78 82 80]
 [92 95 91]
 [75 79 83]]

First Two Rows:
[[85 90 88]
 [78 82 80]]

Last Two Rows:
[[92 95 91]
 [75 79 83]]

First Column:
[85 78 92 75]

Second Column:
[90 82 95 79]

Third Column:
[88 80 91 83]

Middle Matrix:
[[82 80]
 [95 91]]


In [24]:
print("\nDiagonal Elements:")
print(np.diag(marks))


Diagonal Elements:
[85 82 91]


##Exercise 6: Data Types
####Create arrays using integer, float, boolean, Unicode, complex, datetime and timedelta data types.

In [25]:
# Integer Array
int_array = np.array([10, 20, 30, 40], dtype=int)

# Float Array
float_array = np.array([10.5, 20.7, 30.2, 40.9], dtype=float)

# Boolean Array
bool_array = np.array([True, False, True, False], dtype=bool)

# Unicode Array
unicode_array = np.array(["Apple", "Banana", "Cherry"], dtype='U')

# Complex Array
complex_array = np.array([2+3j, 4+5j, 6+7j], dtype=complex)

# Datetime Array
datetime_array = np.array(
    ["2025-01-01", "2025-06-15", "2025-12-31"],
    dtype='datetime64[D]'
)

# Timedelta Array
timedelta_array = np.array([5, 10, 15], dtype='timedelta64[D]')

# Display Arrays and Their Data Types
print("Integer Array:", int_array)
print("Data Type:", int_array.dtype)

print("\nFloat Array:", float_array)
print("Data Type:", float_array.dtype)

print("\nBoolean Array:", bool_array)
print("Data Type:", bool_array.dtype)

print("\nUnicode Array:", unicode_array)
print("Data Type:", unicode_array.dtype)

print("\nComplex Array:", complex_array)
print("Data Type:", complex_array.dtype)

print("\nDatetime Array:", datetime_array)
print("Data Type:", datetime_array.dtype)

print("\nTimedelta Array:", timedelta_array)
print("Data Type:", timedelta_array.dtype)

Integer Array: [10 20 30 40]
Data Type: int64

Float Array: [10.5 20.7 30.2 40.9]
Data Type: float64

Boolean Array: [ True False  True False]
Data Type: bool

Unicode Array: ['Apple' 'Banana' 'Cherry']
Data Type: <U6

Complex Array: [2.+3.j 4.+5.j 6.+7.j]
Data Type: complex128

Datetime Array: ['2025-01-01' '2025-06-15' '2025-12-31']
Data Type: datetime64[D]

Timedelta Array: [ 5 10 15]
Data Type: timedelta64[D]


In [26]:
arr = np.array([0, 1, 2, 0, 5])

print(arr.astype(bool))

[False  True  True False  True]


##Exercise 7: Copy and View
####Create a copy and modify the original array.
####Create a view and modify the original array.
####Use .base to identify ownership.

In [27]:
arr = np.array([10, 20, 30, 40, 50])

print("Original Array:")
print(arr)

Original Array:
[10 20 30 40 50]


In [28]:
# 1. Create a Copy and Modify the Original Array

copy_arr = arr.copy()

# Modify original array
arr[0] = 100

print("\nAfter Modifying Original Array:")
print("Original Array:", arr)
print("Copy Array:", copy_arr)

# Check ownership using .base
print("\nCopy Ownership:")
print(copy_arr.base)


After Modifying Original Array:
Original Array: [100  20  30  40  50]
Copy Array: [10 20 30 40 50]

Copy Ownership:
None


In [29]:
view_arr = arr.view()

# Modify original array
arr[1] = 200

print("\nAfter Modifying Original Array Again:")
print("Original Array:", arr)
print("View Array:", view_arr)

# Check ownership using .base
print("\nView Ownership:")
print(view_arr.base)


After Modifying Original Array Again:
Original Array: [100 200  30  40  50]
View Array: [100 200  30  40  50]

View Ownership:
[100 200  30  40  50]


In [30]:
print("\nMemory Ownership Check:")
print("Copy owns data:", copy_arr.base is None)
print("View owns data:", view_arr.base is None)


Memory Ownership Check:
Copy owns data: True
View owns data: False


##Exercise 8: Shape
####Create arrays of shapes (5,), (2,5), (3,4), (2,3,4) and (2,2,2,2).
####Print the shape of every array.

In [31]:
# Create an array of shape (5,)
array_1 = np.array([1, 2, 3, 4, 5])

# Create an array of shape (2,5)
array_2 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])

# Create an array of shape (3,4)
array_3 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Create an array of shape (2,3,4)
array_4 = np.arange(24).reshape(2, 3, 4)

# Create an array of shape (2,2,2,2)
array_5 = np.arange(16).reshape(2, 2, 2, 2)

In [32]:
print("Array of shape (5,):")
print(array_1)
print("Shape:", array_1.shape)


print("\nArray of shape (2,5):")
print(array_2)
print("Shape:", array_2.shape)


print("\nArray of shape (3,4):")
print(array_3)
print("Shape:", array_3.shape)


print("\nArray of shape (2,3,4):")
print(array_4)
print("Shape:", array_4.shape)


print("\nArray of shape (2,2,2,2):")
print(array_5)
print("Shape:", array_5.shape)

Array of shape (5,):
[1 2 3 4 5]
Shape: (5,)

Array of shape (2,5):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape: (2, 5)

Array of shape (3,4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)

Array of shape (2,3,4):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape: (2, 3, 4)

Array of shape (2,2,2,2):
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
Shape: (2, 2, 2, 2)


##Exercise 9: Reshaping
####Reshape a 24-element array into 4×6, 6×4, 2×3×4 and 3×2×4.
####Flatten it back into a 1D array.

In [33]:
arr = np.arange(1, 25)

print("Original 1D Array:")
print(arr)
print("Shape:", arr.shape)

Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)


In [34]:
# Reshape into 4x6
array_4x6 = arr.reshape(4, 6)

print("\nReshaped Array (4x6):")
print(array_4x6)
print("Shape:", array_4x6.shape)


Reshaped Array (4x6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)


In [35]:
# Reshape into 6x4
array_6x4 = arr.reshape(6, 4)

print("\nReshaped Array (6x4):")
print(array_6x4)
print("Shape:", array_6x4.shape)


Reshaped Array (6x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Shape: (6, 4)


In [36]:
# Reshape into 2x3x4
array_2x3x4 = arr.reshape(2, 3, 4)

print("\nReshaped Array (2x3x4):")
print(array_2x3x4)
print("Shape:", array_2x3x4.shape)



Reshaped Array (2x3x4):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


In [37]:
# Reshape into 3x2x4
array_3x2x4 = arr.reshape(3, 2, 4)

print("\nReshaped Array (3x2x4):")
print(array_3x2x4)
print("Shape:", array_3x2x4.shape)


Reshaped Array (3x2x4):
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
Shape: (3, 2, 4)


In [38]:
# Flatten back into 1D array
flatten_array = array_3x2x4.flatten()

print("\nFlattened 1D Array:")
print(flatten_array)
print("Shape:", flatten_array.shape)


Flattened 1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)


##Exercise 10: Joining Arrays
####Use concatenate(), stack(), hstack(), vstack() and dstack().
####Compare the output shapes.

In [39]:
# Create sample arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

Array 1:
[1 2 3]

Array 2:
[4 5 6]


In [40]:
# 1. concatenate()
concatenated = np.concatenate((arr1, arr2))

print("\nUsing concatenate():")
print(concatenated)
print("Shape:", concatenated.shape)


Using concatenate():
[1 2 3 4 5 6]
Shape: (6,)


In [41]:
# 2. stack()
stacked = np.stack((arr1, arr2))

print("\nUsing stack():")
print(stacked)
print("Shape:", stacked.shape)


Using stack():
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [42]:
# 2. stack()
stacked = np.stack((arr1, arr2))

print("\nUsing stack():")
print(stacked)
print("Shape:", stacked.shape)


Using stack():
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [46]:
# 3. hstack()
hstacked = np.hstack((arr1, arr2))

print("\nUsing hstack():")
print(hstacked)
print("Shape:", hstacked.shape)


Using hstack():
[1 2 3 4 5 6]
Shape: (6,)


In [43]:
# 4. vstack()
vstacked = np.vstack((arr1, arr2))

print("\nUsing vstack():")
print(vstacked)
print("Shape:", vstacked.shape)


Using vstack():
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [44]:
# 5. dstack()
dstacked = np.dstack((arr1, arr2))

print("\nUsing dstack():")
print(dstacked)
print("Shape:", dstacked.shape)


Using dstack():
[[[1 4]
  [2 5]
  [3 6]]]
Shape: (1, 3, 2)


In [47]:
# Comparing Output Shapes
print("\nComparison of Shapes:")
print("concatenate shape:", concatenated.shape)
print("stack shape:", stacked.shape)
print("hstack shape:", hstacked.shape)
print("vstack shape:", vstacked.shape)
print("dstack shape:", dstacked.shape)


Comparison of Shapes:
concatenate shape: (6,)
stack shape: (2, 3)
hstack shape: (6,)
vstack shape: (2, 3)
dstack shape: (1, 3, 2)


##Exercise 11: Employee Dataset
####Perform indexing, slicing, reshape and joining operations on an employee dataset

In [48]:
employees = np.array([
    [101, 25, 50000],
    [102, 30, 60000],
    [103, 28, 55000],
    [104, 35, 75000],
    [105, 40, 90000],
    [106, 32, 65000]
])

print("Employee Dataset:")
print(employees)

print("Shape:", employees.shape)

Employee Dataset:
[[  101    25 50000]
 [  102    30 60000]
 [  103    28 55000]
 [  104    35 75000]
 [  105    40 90000]
 [  106    32 65000]]
Shape: (6, 3)


In [49]:
print("\nFirst Employee Record:")
print(employees[0])

print("\nSalary of Third Employee:")
print(employees[2, 2])

print("\nEmployee ID of Fifth Employee:")
print(employees[4, 0])


First Employee Record:
[  101    25 50000]

Salary of Third Employee:
55000

Employee ID of Fifth Employee:
105


In [50]:
print("\nFirst Three Employees:")
print(employees[:3])

print("\nLast Two Employees:")
print(employees[-2:])

print("\nEmployee IDs:")
print(employees[:, 0])

print("\nEmployee Salaries:")
print(employees[:, 2])


First Three Employees:
[[  101    25 50000]
 [  102    30 60000]
 [  103    28 55000]]

Last Two Employees:
[[  105    40 90000]
 [  106    32 65000]]

Employee IDs:
[101 102 103 104 105 106]

Employee Salaries:
[50000 60000 55000 75000 90000 65000]


In [51]:
# Reshape dataset into 3D array
employee_3d = employees.reshape(2, 3, 3)

print("\nReshaped Employee Dataset (2,3,3):")
print(employee_3d)

print("Shape:", employee_3d.shape)


Reshaped Employee Dataset (2,3,3):
[[[  101    25 50000]
  [  102    30 60000]
  [  103    28 55000]]

 [[  104    35 75000]
  [  105    40 90000]
  [  106    32 65000]]]
Shape: (2, 3, 3)


In [52]:
# Create another employee dataset
new_employees = np.array([
    [107, 27, 52000],
    [108, 29, 58000]
])

print("\nNew Employee Dataset:")
print(new_employees)


# Concatenate rows
combined_employees = np.concatenate((employees, new_employees))

print("\nAfter concatenate():")
print(combined_employees)
print("Shape:", combined_employees.shape)


# Stack arrays vertically
vstack_employees = np.vstack((employees, new_employees))

print("\nAfter vstack():")
print(vstack_employees)
print("Shape:", vstack_employees.shape)


# Stack arrays horizontally
extra_data = np.array([
    [1],
    [2],
    [3],
    [4],
    [5],
    [6]
])

hstack_employees = np.hstack((employees, extra_data))

print("\nAfter hstack() (Adding Department ID):")
print(hstack_employees)
print("Shape:", hstack_employees.shape)


New Employee Dataset:
[[  107    27 52000]
 [  108    29 58000]]

After concatenate():
[[  101    25 50000]
 [  102    30 60000]
 [  103    28 55000]
 [  104    35 75000]
 [  105    40 90000]
 [  106    32 65000]
 [  107    27 52000]
 [  108    29 58000]]
Shape: (8, 3)

After vstack():
[[  101    25 50000]
 [  102    30 60000]
 [  103    28 55000]
 [  104    35 75000]
 [  105    40 90000]
 [  106    32 65000]
 [  107    27 52000]
 [  108    29 58000]]
Shape: (8, 3)

After hstack() (Adding Department ID):
[[  101    25 50000     1]
 [  102    30 60000     2]
 [  103    28 55000     3]
 [  104    35 75000     4]
 [  105    40 90000     5]
 [  106    32 65000     6]]
Shape: (6, 4)


##Exercise 12: Student Marks
####Perform indexing, slicing, shape, reshape and joining operations on student marks.


In [53]:
print("Student Marks:")
print(marks)

print("Shape:", marks.shape)

Student Marks:
[[85 90 88]
 [78 82 80]
 [92 95 91]
 [75 79 83]]
Shape: (4, 3)


In [54]:
# 1. Indexing Operations

# First student's marks
print("\nFirst Student Marks:")
print(marks[0])

# Third student's second subject marks
print("\nThird Student, Second Subject Marks:")
print(marks[2, 1])

# Fourth student's third subject marks
print("\nFourth Student, Third Subject Marks:")
print(marks[3, 2])


First Student Marks:
[85 90 88]

Third Student, Second Subject Marks:
95

Fourth Student, Third Subject Marks:
83


In [55]:
# 2. Slicing Operations

# First two students
print("\nFirst Two Students Marks:")
print(marks[:2])

# Last two students
print("\nLast Two Students Marks:")
print(marks[-2:])

# First subject marks of all students
print("\nFirst Subject Marks:")
print(marks[:, 0])

# Second subject marks of all students
print("\nSecond Subject Marks:")
print(marks[:, 1])

# Third subject marks of all students
print("\nThird Subject Marks:")
print(marks[:, 2])


First Two Students Marks:
[[85 90 88]
 [78 82 80]]

Last Two Students Marks:
[[92 95 91]
 [75 79 83]]

First Subject Marks:
[85 78 92 75]

Second Subject Marks:
[90 82 95 79]

Third Subject Marks:
[88 80 91 83]


In [56]:
# 3. Shape Operations

print("\nOriginal Shape:")
print(marks.shape)


# 4. Reshape Operations

# Reshape into 3D array
marks_3d = marks.reshape(2, 2, 3)

print("\nReshaped Marks Dataset (2,2,3):")
print(marks_3d)

print("Shape:", marks_3d.shape)


Original Shape:
(4, 3)

Reshaped Marks Dataset (2,2,3):
[[[85 90 88]
  [78 82 80]]

 [[92 95 91]
  [75 79 83]]]
Shape: (2, 2, 3)


In [57]:
# Reshape into 1D array
marks_1d = marks.reshape(-1)

print("\nFlattened Marks Array:")
print(marks_1d)

print("Shape:", marks_1d.shape)


Flattened Marks Array:
[85 90 88 78 82 80 92 95 91 75 79 83]
Shape: (12,)


In [58]:
# 5. Joining Operations

# Create additional student marks
new_marks = np.array([
    [88, 91, 90],
    [76, 80, 85]
])

print("\nNew Student Marks:")
print(new_marks)


New Student Marks:
[[88 91 90]
 [76 80 85]]


In [59]:
# concatenate()
combined_marks = np.concatenate((marks, new_marks))

print("\nAfter concatenate():")
print(combined_marks)

print("Shape:", combined_marks.shape)


After concatenate():
[[85 90 88]
 [78 82 80]
 [92 95 91]
 [75 79 83]
 [88 91 90]
 [76 80 85]]
Shape: (6, 3)


In [60]:
# stack()
stacked_marks = np.stack((marks[:2], new_marks))

print("\nAfter stack():")
print(stacked_marks)

print("Shape:", stacked_marks.shape)


# hstack()
extra_subject = np.array([
    [95],
    [88],
    [92],
    [85]
])

hstack_marks = np.hstack((marks, extra_subject))

print("\nAfter hstack() (Adding Fourth Subject):")
print(hstack_marks)

print("Shape:", hstack_marks.shape)


# vstack()
vstack_marks = np.vstack((marks, new_marks))

print("\nAfter vstack():")
print(vstack_marks)

print("Shape:", vstack_marks.shape)


After stack():
[[[85 90 88]
  [78 82 80]]

 [[88 91 90]
  [76 80 85]]]
Shape: (2, 2, 3)

After hstack() (Adding Fourth Subject):
[[85 90 88 95]
 [78 82 80 88]
 [92 95 91 92]
 [75 79 83 85]]
Shape: (4, 4)

After vstack():
[[85 90 88]
 [78 82 80]
 [92 95 91]
 [75 79 83]
 [88 91 90]
 [76 80 85]]
Shape: (6, 3)
