<a href="https://colab.research.google.com/github/harshikala/AI_Engineer_Journey/blob/main/NumPy_Day2_Part4_Harshi_Kala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Exercise 15: Weather Dataset
####Perform indexing, slicing, reshape and joining operations on weather data.

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load and inspect
weather_w1 = pd.read_csv("weather_week1.csv")
print(weather_w1.head())

         date       city  temperature_c  humidity_pct  wind_speed_kmph  \
0  2026-07-01     Jaipur           37.7            62             23.0   
1  2026-07-01      Delhi           39.2            62             16.0   
2  2026-07-01     Mumbai           30.7            40             14.4   
3  2026-07-01  Bengaluru           40.5            68              9.5   
4  2026-07-01    Chennai           26.0            53             22.2   

  condition  
0     Rainy  
1    Cloudy  
2     Windy  
3     Sunny  
4     Rainy  


In [3]:
# Indexing & slicing
# All readings for one city
jaipur_data = weather_w1[weather_w1["city"] == "Jaipur"]

# All readings for one date
july_3_data = weather_w1[weather_w1["date"] == "2026-07-03"]

# Using numpy for fast numeric indexing - convert temperature column to array
temps = weather_w1["temperature_c"].to_numpy()
hot_days_mask = temps > 35
print("Days above 35C:", temps[hot_days_mask])

Days above 35C: [37.7 39.2 40.5 37.8 41.4 36.8 36.1 37.1 40.7 40.7 36.5 35.9 35.8]


In [4]:
# Reshape - pivot so dates are rows, cities are columns, values = temperature
temp_pivot = weather_w1.pivot_table(
    index="date", columns="city", values="temperature_c"
)
print(temp_pivot)

# numpy reshape example: reshape flattened temp array into (days, cities) grid
n_days = weather_w1["date"].nunique()
n_cities = weather_w1["city"].nunique()
temp_grid = weather_w1["temperature_c"].to_numpy().reshape(n_days, n_cities)
print("Reshaped grid:\n", temp_grid)

city        Bengaluru  Chennai  Delhi  Jaipur  Kolkata  Mumbai
date                                                          
2026-07-01       40.5     26.0   39.2    37.7     28.3    30.7
2026-07-02       41.4     36.8   37.8    25.5     31.9    27.0
2026-07-03       25.3     27.9   28.1    28.0     34.4    28.1
2026-07-04       37.1     27.4   31.6    27.4     27.3    36.1
2026-07-05       32.7     27.0   24.9    32.0     40.7    40.7
2026-07-06       25.1     32.6   35.9    36.5     25.0    27.9
2026-07-07       35.8     27.7   31.3    25.2     31.1    34.4
Reshaped grid:
 [[37.7 39.2 30.7 40.5 26.  28.3]
 [25.5 37.8 27.  41.4 36.8 31.9]
 [28.  28.1 28.1 25.3 27.9 34.4]
 [27.4 31.6 36.1 37.1 27.4 27.3]
 [32.  24.9 40.7 32.7 27.  40.7]
 [36.5 35.9 27.9 25.1 32.6 25. ]
 [25.2 31.3 34.4 35.8 27.7 31.1]]


In [5]:
# Join week 1 and week 2 into a continuous dataset
weather_w2 = pd.read_csv("weather_week2.csv")

full_weather = pd.concat([weather_w1, weather_w2], ignore_index=True)
full_weather["date"] = pd.to_datetime(full_weather["date"])
full_weather = full_weather.sort_values(["city", "date"]).reset_index(drop=True)
print(full_weather.head(10))

        date       city  temperature_c  humidity_pct  wind_speed_kmph  \
0 2026-07-01  Bengaluru           40.5            68              9.5   
1 2026-07-02  Bengaluru           41.4            89             14.4   
2 2026-07-03  Bengaluru           25.3            45              8.4   
3 2026-07-04  Bengaluru           37.1            81             21.8   
4 2026-07-05  Bengaluru           32.7            43             21.9   
5 2026-07-06  Bengaluru           25.1            50              3.3   
6 2026-07-07  Bengaluru           35.8            66             14.0   
7 2026-07-08  Bengaluru           39.9            86              7.6   
8 2026-07-09  Bengaluru           27.8            51              6.7   
9 2026-07-10  Bengaluru           33.8            83             10.5   

  condition  
0     Sunny  
1    Cloudy  
2     Humid  
3    Cloudy  
4     Sunny  
5     Windy  
6     Rainy  
7     Rainy  
8     Rainy  
9     Windy  


In [6]:
# Example: average temperature per city across both weeks
avg_temp_by_city = full_weather.groupby("city")["temperature_c"].mean().sort_values(ascending=False)
print(avg_temp_by_city)

city
Bengaluru    34.171429
Mumbai       33.942857
Delhi        32.950000
Kolkata      32.628571
Jaipur       30.835714
Chennai      29.200000
Name: temperature_c, dtype: float64
